### ISSUE TITLE
New Emulators

### ISSUE THREAD

**Issue by mfwhite** [neilmunday/pes#11]
Hello Neil, I'm glad to see that continues to improve the PES system. I would like to know if you have plans to add new emulators like Dreamcast and PSP and update the Mame emulator for mame 2003 from libretro as it is showing compatibility and better performance in games. Thanks for listening.

**Comment by neilmunday** [comment]
Hi. PES 2.0 is currently in BETA as you can probably tell from the issues that are open at present. I didn't have any immediate plans to add Dreamcast or PSP but I will add them to the list, include MAME 2003.

**Comment by neilmunday** [comment]
If you'd like to try out the PES 2.0 BETA as it stands, then ping me an e-mail using pes@mundayweb.com

I was planning to do a public BETA once the existing teething issues have been resolved.

**Comment by neilmunday** [comment]
I've been looking at PPSSPP over the last week to provide PSP emulation. The Libretro version does not run as well as the standalone version. However, the standalone version's control pad support when using SDL isn't great.

I have therefore been working on adding SDL game controller API support for PPSSPP (just like PES has).

If anyone is interested, see: https://github.com/hrydgard/ppsspp/issues/8986

**Comment by unknownbrackets** [comment]
Yeah, the libretro version is based on an older version (PPSSPP v1.0.1 maybe?) and contains an important bug for Raspberry Pi 3 related to memory mapping that hits performance hard.

Also see libretro/libretro-ppsspp#71.

-[Unknown]

**Comment by neilmunday** [comment]
@unknownbrackets thanks for the info. I have yet to try either on my Raspberry Pi. At the moment I've been testig the Libretro and standalone versions under Linux. With the Libretro version I have found some games produce no video unlike the standalone version which seems to work well and also runs a bit faster.

**Comment by neilmunday** [comment]
So PPSSPP on Raspberry Pi 3 testing results under Arch Linux:
RetroArch core fails to launch. I had to rebuild ffmpeg for the Raspberry Pi 3 (arm7) by using a host compile rather than the cross compile and also add "-fPIC" to allow the libraries to link. Sadly, the core fails to load due to an undefined NEON symbol which is odd as the process does have these features.

For the standalone version of PPSSP the program builds and runs, however it is not very playable, e.g. Grand Theft Auto despite adjusting various settings.

Under Linux (x86_64) the standalone version works well. The libretro core is a bit hit and miss as some games display no video.

For now I think I am going to have to drop PPSSPP from being included in PES 2.1 for the Raspberry Pi.

**Comment by unknownbrackets** [comment]
http://forums.ppsspp.org/showthread.php?tid=2108&pid=118327#pid118327

Someone made a list of a few games - yes, Grand Theft Auto and God of War are games that are likely to be unplayable with that hardware.  Honestly I'm surprised at how many games ARE playable on that video card.

-[Unknown]

**Comment by neilmunday** [comment]
Thanks for the list. Little Big Planet is pretty playable with frame skipping set to 2. I will add it for now, but only for RPi2/3.

**Comment by neilmunday** [comment]
MAME 2003 added as of: 84f42f6  

Will be in PES 2.1.

**Comment by neilmunday** [comment]
PPSSPP added as of: fad4f6acf25a8fe47c74f3bc08a4031ab55549d5

Will be in PES 2.1 (RPi2/3 only).

**Comment by neilmunday** [comment]
MAME 2003 and PPSSPP in PES 2.1 BETA (RPi2/3 only).

Dreamcast support will be added as a separate issue.
