### ISSUE TITLE
Add PS3 battery level status

### ISSUE THREAD

**Issue by neilmunday** [neilmunday/pes#29]
As suggested by @nwildner.

Power level of PS3 control pads can be found via: https://wiki.gentoo.org/wiki/Sony_DualShock#Battery_charge_level

**Comment by nwildner** [comment]
Icons exists at Game-Icons:  [100%](http://game-icons.net/priorblue/batteries/battery-100.html), [75%](http://game-icons.net/priorblue/batteries/battery-75.html), [50%](game-icons.net/priorblue/batteries/battery-50.html) and [25%](http://game-icons.net/priorblue/batteries/battery-25.html) that could be imported to the `resources` dir as they are all CC BY 3.0 licensed :)

`bluetoothctl` does not gives us an "order" of what bluetooth device is player 1, 2 3...(to me, they apear as alphabetical order of mac address trusted)  and `usb id` is not very usefull in this case since it's used only during pair process.

How could we achieve the `/sys/class/power_supply/sony_controller_battery_<BT_MAC_ADDRESS>/capacity` linking between player order and bt mac address?

**Comment by neilmunday** [comment]
So, the battery power above is only for when connected via Bluez rather than sixad. It would be nice to be able to handle both methods.

**Comment by neilmunday** [comment]
This seems to work when getting the battery level when using sixad:

`sudo hcidump -R -O -i 0 | head -n 5 | tail -n 1 | awk '{ print $1 }'`

**Comment by neilmunday** [comment]
Damn, I thought this might save the day as I already use SDL2: https://wiki.libsdl.org/SDL_JoystickCurrentPowerLevel, however it can't get the power level of the PS3 control pads when connected via Bluez or sixad.

**Comment by neilmunday** [comment]
If I can get issue #30 up and running then we can settle on using just Bluez rather than sixad. It may also be possible to monitor dbus for when control pads connect via Bluetooth and when SDL sees a control pad connect. The two events should happen at almost the same time so this could be used to tie up the SDL joystick instance with the Bluetooth device.

**Comment by neilmunday** [comment]
Not being considered for PES 2.x anymore. Development has switched to PES 3.0: https://github.com/Pi-Entertainment-System/pes-gui

PES 3.0 does have a DBus module so it might be possible to query the power status this way - this needs to be investigated along with trying the SDL2 power level function with latest version of SLD2.
